---
kind: Service
apiVersion: v1
metadata:
  name: agnhost
  labels: &labels
    app: agnhost
spec:
  selector: *labels
  ports:
    - protocol: TCP
      port: {{ .Values.firstPort }}
      targetPort: {{ .Values.firstPort }}
      name: first-port
    - protocol: TCP
      port: {{ .Values.secondPort }}
      targetPort: {{ .Values.secondPort }}
      name: second-port

